langchain4j:
  open-ai:
    chat-model:  #非流式调用，默认使用chat-model
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true
    streaming-chat-model: #流式调用，默认使用chat-model
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus
      log-requests: true
      log-responses: true
    embedding-model:   #文本嵌入模型，默认使用embedding-model
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: text-embedding-v3
      log-requests: true
      log-responses: true
      max-segments-per-batch: 10  # 最大分段数，默认10

  community:
    redis:
      host: 192.168.100.128
      port: 6379
logging:
  level:
    dev.langchain4j: debug

spring:
  data:
    redis:
      host: 192.168.100.128
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true